### ISSUE TITLE
[아이템 1]  생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Effective-Java#1]
아이템 : 생성자 대신 정적 팩터리 메서드를 고려하라

**Comment by kimhanui** [comment]
9pg

"새로 생성한 인스턴스를 캐싱하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다."

에서 인스턴스 캐싱이 무엇인지 예시랑 같이 설명해주시면 감사

**Comment by kimhanui** [comment]
9pg

`플라이웨이트 패턴`이 무엇인지 개념, 예시가 있으면 좋을 것 같음

**Comment by kimhanui** [comment]
10pg

"... 이름이 _Type_ 인 인터페이스를 반환하는 정적 메서드가 필요하면,  _Types_ 라는 (인스턴스화 불가인) 동반클래스(compoanion class)를 만들어 그 안에 정의하는 것이 관례였다."

에서 `동반클래스` 개념을 몰라서그런지 이 문장이 이해되지 않습니다

**Comment by kimhanui** [comment]
12pg
`컴포지션을 사용(아이템18)`하는 것의 개념과 이 것이 왜 장점으로 연결되는지 알면 좋을 것 같습니다.

**Comment by cheewr85** [comment]
[질문]
8pg 책에서 짧게 예시를 든 것처럼 정적 팩터리 메서드에 대한 추가적인 다른 예시가 있는지 궁금함

**Comment by cheewr85** [comment]
[질문]
9pg 인스턴스 캐싱 & 플라이웨이트 패턴 위의 질문과 동일

**Comment by cheewr85** [comment]
[질문]
9pg 앞에서 불변 클래스 인스턴스를 미리 만들어 놓는 것과 불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장한다는 것이 어떤 구조와 코드로 되어있는지 예시가 궁금함

**Comment by cheewr85** [comment]
[질문]
10pg 인터페이스 기반 프레임워크를 만드는 핵심 기술이라고 하였는데 여기서 인터페이스 기반 프레임워크가 무엇이고 예시가 무엇인지 궁금함

**Comment by cheewr85** [comment]
[질문]
10pg 인스턴스 불가 동반 클래스를 둘 이유가 없다. 동반 클래스에 두었던 public 정적 멤버들 상당수를 그냥 인터페이스 자체에 두면 되는 것, 별도의 package-private 클래스로 두는 것, 이렇게 쓰여진 부분에 대해서 실제로 어떻게 쓰이면서 활용되는지에 대한 부분이 궁금함

**Comment by cheewr85** [comment]
[질문]
11pg 서비스 제공자 프레임워크의 컴포넌트와 이 구조 자체에 대해서 전반적인 구조의 흐름과 어떻게 돌아가는지가 궁금함

**Comment by cheewr85** [comment]
[질문]
12pg 브리지 패턴, 의존 객체 주입 프레임워크 등 서비스 제공자 프레임워크 패턴에 변형에 대해서 이 부분이 앞서 말한 서비스 제공자 프레임워크와 더불어서 어떻게 응용이 되면서 쓰인것인지 궁금함

**Comment by cheewr85** [comment]
> [답변] 8pg 책에서 짧게 예시를 든 것처럼 정적 팩터리 메서드에 대한 추가적인 다른 예시가 있는지 궁금함

- 객체 생성을 흔히 사용하는 생성자가 아닌 정적 메서드로 하는 것을 정적 팩터리 메서드라고 함
- 책의 예제의 경우 Boolean에서 boolean 값을 넘기면 Boolean 객체 참조로 변환함, 이를 자세히 보면

![image](https://user-images.githubusercontent.com/32586985/150892752-6c632b46-da00-469d-863c-82fdee71d929.png)

- valueOf 메서드로 TRUE나 FALSE를 리턴할 수 있는데 이를 다시 더 보면

![image](https://user-images.githubusercontent.com/32586985/150892803-a6b9ca30-735f-4b00-950a-bbc35f605062.png)

- 결국 저 valueOf 메서드를 통해서 객체 생성을 new 키워드 흔히 생성자로 하는 방식이 아닌 valueOf 메서드를 이용해 객체를 만들 수 있게 된 것임

- 여기서 String 객체 또한 동일하게 정적 팩토리 메서드의 예시로 볼 수 있음

- 예시로 만약 int를 String으로 변환한다고 할 때 아래와 같이 String 객체로 만들 수 있음, 근데 여기서 포인트는 valueOf라는 메서드로 쓴 것

![image](https://user-images.githubusercontent.com/32586985/150893571-a28e5063-b343-4840-8a65-d690f3135adc.png)
![image](https://user-images.githubusercontent.com/32586985/150893590-042e0a72-7f6e-410b-a436-8b4f32c23bc7.png)

**Comment by cheewr85** [comment]
> [답변] 9pg 인스턴스 캐싱 & 플라이웨이트 패턴 위의 질문과 동일

- 캐시의 사전적인 정의는 데이터나 값을 미리 복사해 놓는 임시장소로 볼 수 있음, 컴퓨터 과학에서 흔히 말하는 캐시

- 캐싱은 이러한 캐시라는 작업을 하는 것을 의미함

- 그러면 여기서 인스턴스 캐싱은?

- 자바에서 참조타입을 사용하는 Wrapper Class가 존재함, 여기서 Primitive Type으로 흔히 쓰는 int, byte, short, float... 등을 Wrapper Class로 만든 것, 이는 List를 예를 들면 List에서는 타입을 명시해주기 위한 Generic<T>을 사용함, 근데 여기서 `List<int>`로 쓰면 안됨, Generic안에 들어가는 값으로는 객체만 가능하기 때문에

- 그래서 Wrapper Class인 Interger를 사용해서 `List<Integer>`를 써야함, 이는 다양한 라이브러리와 프레임워크의 활용을 위해서 제공을 하는 것임, 즉 객체로써 사용을 하는 것임

- 여기서 한가지 생각나는 부분이 인스턴스는 각각의 주소를 가지는데, 그렇다면 Wrapper Class로 생성한 값(인스턴스)들은 서로 다른 주소값을 가진다고 생각해서 `equals`를 써야 할 것 같지만 `==`를 써도 같음, 즉 동일한 주소를 가지고 있다는 것인데 이는 캐싱 덕분에 가능한 일임

![image](https://user-images.githubusercontent.com/32586985/150894689-91169663-d0ff-4560-90b6-9878eac66235.png)

- Integer소스 코드를 보면 위와 같이 기본값(-128~127) 사이의 Integer 인스턴스를 미리 생성하여 cache 배열에 저장하는 것을 볼 수 있음

![image](https://user-images.githubusercontent.com/32586985/150894805-cab82eef-d95e-45d8-8670-ab9698aacfec.png)

- 이 IntegerCache를 활용하는 valueOf 메소드는 위와 같은데 이를 보면 low와 high 값 사이의 경우 IntegerCache의 cache에 저장된 값을 반환하고 그 외의 경우 새로 Integer 인스턴스를 생성하여 반환함

- 캐싱해둔 범위 내의 숫자일 경우 캐싱한 인스턴스를 반환하고 범위 밖의 수일 경우 새로 인스턴스를 생성하여 반환하는 방식임

- 즉, 질문에서 새로 생성한 인스턴스를 캐싱하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다는 이유가 위와 같은 로직으로 돌아가기 때문임

--------------

- 플라이웨이트 패턴은 어떤 클래스의 인스턴스 한 개만 가지고 여러 개의 가상 인스턴스를 제공하고 싶을 때 사용하는 패턴이라고 함, 이를 통해 인스턴스를 가능한 대로 공유시켜 쓸데없이 new 연산자를 통한 메모리 낭비를 줄이는 방식임

- 이것이 정적 팩터리 메서드의 방식과 비슷한 기법이라고 하였는데 그렇게 볼 수 있는 이유는 정적 팩터리 메서드 자체가 new 혹은 기존 생성자 형식으로 객체를 만들지 않고 메서드를 통해서 만드는 것이기 때문에 new 연산자를 통한 메모리 낭비를 줄이고 인스턴스 캐싱 방식 역시 위에서 설명한 방식을 보면 이 설명과 일맥상통함

- 즉, 플라이웨이트 기법과 비슷한 기조를 보인다고 볼 수 있는 것임

**Comment by cheewr85** [comment]
> [질문] 9pg 앞에서 불변 클래스 인스턴스를 미리 만들어 놓는 것과 불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장한다는 것이 어떤 구조와 코드로 되어있는지 예시가 궁금함

- 불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장한다는 말은 이미 위의 Wrapper Class를 설명할 때 증명이 됐음

- 인스턴스는 각각의 주소를 가진다고 하였는데 Wrapper Class에서는 인스턴스 캐싱으로 이런 일이 발생하지 않는다고 말하였음

- 이는 즉, 질문에서처럼 불변 값 클래스에서 동치인 인스턴스가 단 하나뿐임을 보장을 무조건 해준다고 볼 수 있음, 대표적인 불변 값 클래스도 String, Integer, Boolean 등의 Wrapper Class임

**Comment by cheewr85** [comment]
> [질문] 10pg 인터페이스 기반 프레임워크를 만드는 핵심 기술이라고 하였는데 여기서 인터페이스 기반 프레임워크가 무엇이고 예시가 무엇인지 궁금함

- 인터페이스 기반이라는 용어를 좀 더 생각해본다면 이는 인터페이스 구현 클래스를 사용하는 것이 아니라, 인터페이스를 사용하여 구체적인 클래스를 사용하지 않는 것을 의미함

- 그러면 인터페이스 기반 프레임워크는 어떻게 보면 안드로이드 개발, 스프링 개발등 직접적인 구현과 개발을 위해서 쓰는 프레임워크들이 그 기반이로 볼 수도 있음

- 안드로이드 개발하는데 있어서 이미 구현된 인터페이스들을 구현하면서 만드는 요소들이 있기 때문에

**Comment by riyenas0925** [comment]
> [질문] 9pg 인스턴스 캐싱 & 플라이웨이트 패턴 위의 질문과 동일

https://velog.io/@lxxjn0/%EB%B0%98%EB%B3%B5%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%EB%90%98%EB%8A%94-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%BA%90%EC%8B%B1%ED%95%98%EA%B8%B0
