### ISSUE TITLE
[아이템 11] equals를 재정의하려거든 hashcode도 재정의하라

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Effective-Java#12]
아이템 : equals를 재정의하려거든 hashcode도 재정의하라

- [x] #48

**Comment by kimhanui** [comment]
[질문]
68pg
`설사 두 인스턴스를 같은 버킷에 담았더라도 get 메서드는 여전히 null을 반환하는데, HashMap은 해시코드가 다른 엔트리끼리는 동치성 비교를 시도조차 하지 않도록 최적화되어 있기 때문이다.`
- 두 인스턴스를 같은 버킷에 담았는데 `왜` null을 반환한다는건지 이해가 안돼요
- HashMap이 도이성 비교를 언제 한다는지 잘 모르겠어요
