### ISSUE TITLE
Correction Note

### ISSUE THREAD

**Issue by kimhanui** [Study-Mornda/Effective-Java#13]
## 스터디 중 생긴 질문들을 이 곳에 모아놓고 주기적으로 복습합니다.

`github-action`으로 각 Item별 이슈에 질문 등록시 이 이슈에 자동 코멘트 추가되게 했습니다.

사용 방법: 
  - **동작 조건:** 각 Item 별 이슈에 코멘트로 질문 등록시 **`[질문]` 키워드로 `시작`하게 작성합니다.**  
    ( 그래서 이제 `질문`과 `답변` 코멘트를 따로 달아야할 듯....)
  - 등록 후 `🚀 reaction`이 생기면 직접 확인하지 않고도 오답노트에 등록된 것을 알 수 있습니다.
 

오답노트에 기록된 질문은:
  - 원래 주소의 코멘트로 만들어진 적이 없으면 `생성`, 있으면 `업데이트` 됩니다.
  - `질문자`, `원래 주소의 코멘트`를 첨부해서 당시 답변을 바로 참조할 수 있게 했습니다.

**Comment by kimhanui** [comment]
https://github.com/Study-Mornda/Effective-Java/issues/1#issuecomment-901859212
9pg

"새로 생성한 인스턴스를 캐싱하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다."

에서 `인스턴스 캐싱`이 무엇인지 예시랑 같이 설명해주시면 감사

**Comment by kimhanui** [comment]
> @kimhanui, https://github.com/Study-Mornda/Effective-Java/issues/2#issuecomment-901656768

16pg 

"자바빈즈패턴에서는 객체 하나를 만들려면 메서드를 여러 개 호출해야 하고, 객체가 완전히 생성되지 전까지는 일관성(consistency)이 무너진 상태에 놓이게 된다."에서 일관성의 의미? :

**Comment by kimhanui** [comment]
> @riyenas0925, https://github.com/Study-Mornda/Effective-Java/issues/2#issuecomment-901659971

19pg
불변, 불변식이란

**Comment by kimhanui** [comment]
> @riyenas0925, https://github.com/Study-Mornda/Effective-Java/issues/2#issuecomment-901679519

Immutable Class는 무엇인지, Immutable Class 장단점

**Comment by kimhanui** [comment]
> @kimhanui, https://github.com/Study-Mornda/Effective-Java/issues/2#issuecomment-901692260

20pg

```java
public abstract class Pizze{
  // ..
  abstract static class Builder<T extends Builder<T>> { ... }
  // ..
}
```
에서 "재귀적 타입 한정" 이란?

**Comment by riyenas0925** [comment]
> > @kimhanui, [#1 (comment)](https://github.com/Study-Mornda/Effective-Java/issues/1#issuecomment-901859212)
> 
> [질문]
> 
> 9pg "새로 생성한 인스턴스를 캐싱하여 재활용하는 식으로 불필요한 객체 생성을 피할 수 있다."
> 
> 에서 `인스턴스 캐싱`이 무엇인지 예시랑 같이 설명해주시면 감사
