### ISSUE TITLE
[아이템 12] toString을 항상 재정의하라 

### ISSUE THREAD

**Issue by kimhanui** [Study-Mornda/Effective-Java#14]
아이템 : toString을 항상 재정의하라

- [x] #49
- [x] #50

**Comment by kimhanui** [comment]
[질문]
75pg `정적 유틸리티 클래스(아이템 4)는 toString을 제공할 이유가 없다`의 의미는?

**Comment by kimhanui** [comment]
https://github.com/Study-Mornda/Effective-Java/issues/14#issuecomment-914188675 답변

아이템4(인스턴스화를 막으려거든 private 생성자를 사용하라) 에선 `정적 멤버만 담은 유틸리티 클래스는 인스턴스로 만들어 쓰려고 설게한 게 아니다` 라고 하고 있다.

이를 바탕으로 생각해보면 정적 클래스는 인스턴스를 생성하지 않으므로 내부 값이 달라지지도, `toString`으로 확인할 필요도 없으므로 toString을 제공할 이유가 없다고 하는 것 같다.

**Comment by kimhanui** [comment]
[질문]
75pg `대부분의 열거 타입(아이템34)도 자바가 이미 완벽한 toString을 제공하니 따로 재정의하지 안항도 된다`고 하는데   
예시로 어떤게 있을까?

**Comment by riyenas0925** [comment]
```
public enum LogLevel {
  VERB,
  INFO,
  DEBUG,
  WARN,
  ERROR,
}

public static void main(String[] args) {
  System.out.println(LogLevel.INFO.name());
}
```
