### ISSUE TITLE
[아이템3] 무상태 객체나 설계상 유일해야 하는 시스템 컴포넌트의 개념

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Effective-Java#20]
[질문]
23pg 3줄

"싱글턴의 전형적인 예로는 함수와 같은 무상태(stateless)객체나 설계상 유일해야 하는 시스템 컴포넌트를 들 수 있다."
에서 무상태 객체의 개념을 몰라서 이 문장이 이해가 안감

무상태 객체의 개념, 이게 어떻게 싱글턴과 연결되는지 알려주면 좋게슴

**Comment by cheewr85** [comment]
- 아이템 3의 주요 주제는 싱글턴임을 보증을 하는 것이 주된 주제임

- 여기서 무상태 객체로 설계로써 싱글턴을 쓴다고 하였는데 이 무상태 객체는 무엇인가 더 알아봄

- 구체적으로 이 객체는 특정 클라이언트에 의존적이거나 값을 변경할 수 있는 필드가 있거나 하면 안되고 가급적 읽기만 해야하는 상태를 말함

- 즉 여기서 만약 싱글턴을 무상태 객체로 사용하지 않는다고 할 경우, 예를 들어 주문 금액을 처리해야하는 상태에서 무상태 객체를 사용하지 않으면 해당 금액 변수가 계속 변함, 즉, A에서 10000원을 한 경우와 B에서 20000원을 했을 때 무상태 객체가 아니므로 B에서 주문한 것이 그대로 반영되어 A에서도 20000원이 된다는 것

- 이를 무상태 객체로 만들어두면 이런식으로 교차로 쓴다고 하더라도 문제가 발생하지 않음, 이런 객체 간의 동기화 이슈에 유의해야함

- 그리고 설계상 유일해야 하는 시스템 컴포넌트로써 싱글턴을 예시를 들었는데 이 방식은 책 예시에서 private 생성자로 public static final 필드인 Elvis.INSTANCE를 초기화 할 때 딱 한 번 호출되는데 이 의미 자체가 인스턴스가 전체 시스템에서 하나뿐임이 보장되는데 싱글턴의 예시로 그러한 설계를 해야한다는 목적에 부합함

------

## 참고
https://studyandwrite.tistory.com/386

**Comment by riyenas0925** [comment]
### 무상태 객체(Stateless Object)

```java
* 클래스 내부에 인스턴스 변수가 없는 객체를 의미

```java
class Stateless {
    void test() {
        System.out.println("Test!");
    }
}
```
```java
class Stateless {
    //No static modifier because we're talking about the object itself
    final String TEST = "Test!";

    void test() {
        System.out.println(TEST);
    }
}
```

### 무상태 객체의 장점
* 스레드에 안전

### 불변 객체와의 차이점
* 불변 객체 : 런타임 시점에서 값을 가진다.
* 무상태 객체 : 컴파일 시점에서 값을 가진다.

### 참고
* [What is Stateless Object in Java?](https://stackoverflow.com/questions/9735601/what-is-stateless-object-in-java)

```
