### ISSUE TITLE
[아이템3] API를 바꾸지 않고도 싱글턴이 아니게 변경할 수 있다는 점

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#23]
[질문]
24pg

정적 팩터리 방식의 장점으로 API를 바꾸지 않아도 싱글턴이 아니게 변경할 수 있다는 점이 장점이라고 하였는데 이 부분이 장점으로 될 수 있는 구체적 예시 API를 바꾸는 방식과 비교했을 때

**Comment by cheewr85** [comment]
- 여기서 API를 바꾸지도 않아도 싱글턴이 아니게 변경할 수 있다고 하였는데 이 말은 정적 팩터리 방식이 기저에 깔려있음

- 참고로 찾은 코드를 바탕으로 정적 팩터리 방식의 싱글턴 인스턴스를 얻는 방법은 아래와 같음
```java
public class YongCoding{
	
    // 인스턴스를 얻기 위해서는 정적 팩토리 메소드를 이용해야한다.
	private static final YongCoding INSTANCE = new YongCoding();
    
    // private 생성자
    private YongCoding(){
    // 생략!
	}
    
    // 정적 팩토리 메소드 방식으로 싱글턴 객체 얻기
   	public static YongCoding getInstance(){
    	return INSTANCE;
    }
}
```

- 여기서 싱글턴이 아니게 변경을 하는 것이 새로운 객체를 생성해서 반환한다고 하면 아래와 같이 변경할 수 있음
```java
public class YongCoding{
	
    // 인스턴스를 얻기 위해서는 정적 팩토리 메소드를 이용해야한다.
	private static final YongCoding INSTANCE = new YongCoding();
    
    // private 생성자
    private YongCoding(){
    // 생략!
	}
    
    // 정적 팩토리 메소드 방식으로 싱글턴 객체 얻기
   	public static YongCoding getInstance(){
    	return new YongCoding(); // 변경 부분
    }
}
```

- 여기서 그럼 API를 바꾸지 않고 싱글턴이 아니게 변경했다는 것 점은? 바로 이 클래스를 사용하는 다른 클래스들을 본다면 알 수 있음

```java
// 시그니쳐의 변경이 없다.
// 클라이언트는 이 코드가 싱글턴인지 새로운 객체를 생성해서 반환하는지 상관없이 그대로 사용해도 아무 문제가 없다.
YongCoding.getInstance();
```

- 즉, `getInstance()` 사용에 있어서 아무런 문제가 없음, 이 장점이 위에서 말한대로 API를 바꾸지 않아도 이렇게 변경할 수 있는 방식을 의미한 것임

------
## 참고
https://primayy.tistory.com/60

**Comment by riyenas0925** [comment]
정적 팩터리 방식의 코드를 보면 아래와 같습니다.

```java
public class Singleton {
    private static final Singleton INSTANCE = new Singleton();

    private Singleton() { }

    public static Singleton getInstance() {
        return INSTANCE;
    }
}
```

이때 Client 코드를 보면 Singleton.getInstance()로 싱글턴 객체를 가져온다. 하지만 호출하는 스레드별로 다른 인스턴스를 넘기게 변경하고 싶다면 Singleton.getInstance()를 사용하는 코드는 유지한채 Singleton 클래스의 getInstance 메서드의 구현 방법을 변경하면 된다.

```Java
public static Singleton getInstance() {
    //return INSTANCE;
    //return new Singleton();
}
```
