### ISSUE TITLE
[아이템3] 제네릭 싱글턴 팩터리의 개념

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#24]
[질문]
24pg

제네릭 싱글턴 팩터리에 대해서 아이템 30에서 다룰 내용이지만 이해를 위해서 간단한 개념에 대한 질문

**Comment by cheewr85** [comment]
- 제네릭 싱글턴 팩토리는 제네릭으로 타입 설정 가능한 인스턴스를 만들어두고, 반환 시에 제네릭으로 받은 타입을 이용해 타입을 결정하는 것을 말함

- 요청한 타입 매개변수에 맞게 매번 그 객체의 타입을 바꿔주는 정적 팩토리를 만드는 것

```java
public class GenericFactoryMethod { 
public static final Set EMPTY_SET = new HashSet(); 

        public static final <T> Set<T> emptySet() { 
               return (Set<T>) EMPTY_SET; 
        } 
}
```
- 위와 같이 제네릭으로 만들어두는 것

- 그러면 아래와 같이 코드를 써보면 여러 타입으로 내부 객체를 받아도 에러가 나지 않음, 큰 유연성을 제공해줌

```java
@Test public void genericTest() { 
        Set<String> set = GenericFactoryMethod.emptySet(); 
        Set<Integer> set2 = GenericFactoryMethod.emptySet(); 
        Set<Elvis> set3 = GenericFactoryMethod.emptySet(); 

        set.add("ab"); 
        set2.add(123); 
        set3.add(Elvis.INSTANCE); 

        String s = set.toString(); 
        System.out.println("s = " + s); 
}
```

------
## 참고
https://jake-seo-dev.tistory.com/13?category=909023
https://jackjeong.tistory.com/56

**Comment by riyenas0925** [comment]
`uses unchecked or unsafe operations` 오류의 경우 @SuppressWarnings("unchecked")를 붙여주면 무시할 수 있다.
