### ISSUE TITLE
[아이템3] 정적 팩터리의 메서드 참조를 공급자로 사용하는 점

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#25]
[질문]
24pg

정적 팩터리의 메서드 참조를 공급자로 사용할 수 있다는 점에서 공급자로 사용한다는 것이 정확히 어떻게 공급자로써 쓴다는 것인지에 대한 예시

**Comment by cheewr85** [comment]
- 여기서 이를 이해하기 위해서 Supplier에 대해서 더 찾아봄

- Supplier는 자바에서 함수형 인터페이스로 추상메서드는 모두 매개변수를 받는데 이 Supplier의 경우 매개변수를 받지 않고 단순히 무엇인가를 반환하는 추상메서드가 존재함

- 즉 함수형 방식의 일환으로 Supplier가 제네릭 타입이므로 어떠한 것이든 받아서 리턴할 수 있음

- 그러면 그런 의미와 더불어서 정적 팩터리 메서드 참조를 공급자로 사용한다는 것은 예시코드와 함께 볼 수 있음
```java
public class Elvis {
    private static final Elvis INSTANCE = new Elvis();
    private Elvis() { }
    public static Elvis getInstance() { return INSTANCE; }
}
```

- 여기서 getInstance()를 통해 항상 같은 인스턴스를 리턴하는데 싱글턴으로 이 메서드 참조를 함수형으로써 쓴다면 `Elvis::getInstance`로 쓸 수 있는데 이 상황에서 공급자로 `Supplier<Elvis>`로 쓸 수 있음을 의미함

-----
## 참조
https://m.blog.naver.com/zzang9ha/222087025042
https://dlsrb6342.github.io/2019/03/01/Effective-Java-3rd-ITEM-3/

**Comment by riyenas0925** [comment]
```Java
public class Main {
    public static void main(String[] args) {
        Supplier<Singleton> supplier = Singleton::getInstance;

        System.out.println(supplier.get().getClass().getSimpleName()); // 여기서는 Singleton 클래스의 이름을 출력한다.
    }
}
```
