### ISSUE TITLE
[아이템 5 - 질문] Supplier 인터페이스가 팩터리를 표현한 완벽한 예, 이 예시에 대해서

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#29]
[질문] 
29pg

Supplier<T> 인터페이스가 팩터리를 표현한 완벽한 예라고 하였는데 이게 어떻게 연관되서 예시로써 쓰이는지

**Comment by cheewr85** [comment]
- 팩터리는 앞서 다룬 주제에서 말한대로 특정 타입의 인스턴스를 반복해서 만들어 주는 객체를 말함

- 여기서 Supplier 인터페이스가 팩터리를 표현한 완벽한 예라고 하였는데, 여기서 Supplier<T> 인터페이스는 명시한 타입의 하위 타입이라면 무엇이든 생성할 수 있는 팩터리를 만들 수 있음

- 그래서 아이템에서 팩터리를 표현한 완벽한 예라고 하였고 해당 아이템에서 의존 객체 주입을 다루는데 여기서 팩터리 메서드 패턴이 또한 의존 객체 주입 패턴을 응용한 것임, 그래서 이 예시로 볼 수 있음

------

### 참조
https://dahye-jeong.gitbook.io/java/java/effective_java/2021-01-16-dependency-injection

**Comment by riyenas0925** [comment]
팩터리는 호출할 때마다 특정 타입의 인스턴스를 반복해서 만들어주는 객체를 의미합니다. 즉 팩터리 메서드 패턴을 구현한 것인데 Java 8에서 소개한 Supplier<T> 인터페이스가 팩터리를 표현한 완변한 예입니다.

Supplier<T>를 입력으로 받는 메서드는 일반적으로 한정적 와일드 카드 타입(?)을 사용해 팩터리의 타입 매개변수를 제한해야 합니다. 이방식을 사용해 클라이언트는 자신이 명시한 타입의 하위타입이라면 무엇이든 생성할 수 있는 팩터리를 넘길 수 있습니다.

```java
public interface Shape {
   void draw();
}
```

```java
public class Rectangle implements Shape {

   @Override
   public void draw() {
      System.out.println("Inside Rectangle::draw() method.");
   }
}

public class Circle implements Shape {

   @Override
   public void draw() {
      System.out.println("Inside Circle::draw() method.");
   }
}
```
```java
public class ShapeFactory {

  final static Map<String, Supplier<Shape>> map = new HashMap<>();
  static {
    map.put("CIRCLE", Circle::new);
    map.put("RECTANGLE", Rectangle::new);
  }   
  public Shape getShape(String shapeType){
     Supplier<Shape> shape = map.get(shapeType.toUpperCase());
     if(shape != null) {
       return shape.get();
     }
     throw new IllegalArgumentException("No such shape " + shapeType.toUpperCase());
  }
}
```
```java
public class Main {

   public static void main(String[] args) {

     Supplier<ShapeFactory> shapeFactory =  ShapeFactory::new;

     //call draw method of circle
     shapeFactory.get().getShape("circle").draw();

     //call draw method of Rectangle
     shapeFactory.get().getShape("rectangle").draw();      
   }
}
```

### 참조
[The Factory Pattern Using Lambda Expressions in Java 8](https://dzone.com/articles/factory-pattern-using-lambda-expression-in-java-8)
