### ISSUE TITLE
[아이템3] private 생성자나 열거 타입으로 싱글턴임을 보증하라 

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Effective-Java#3]
아이템 : private 생성자나 열거 타입으로 싱글턴임을 보증하라 

질문
- [x] #20
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27

**Comment by kimhanui** [comment]
23pg 3줄

"싱글턴의 전형적인 예로는 함수와 같은 무상태(stateless)객체나 설계상 유일해야 하는 시스템 컴포넌트를 들 수 있다."
에서 `무상태 객체`의 개념을 몰라서 이 문장이 이해가 안감 
- 무상태 객체의 개념, 이게 어떻게 싱글턴과 연결되는지 알려주면 좋게슴

**Comment by riyenas0925** [comment]
### 무상태 객체(Stateless Object)
* 클래스 내부에 인스턴스 변수가 없는 객체를 의미

### 무상태 객체의 장점
* 

### 참고

**Comment by riyenas0925** [comment]
리플렉션을 사용하면 private 생성자를 호출할 수 있다.

```java
@Test
@DisplayName("리플렉션을 사용하면 private 생성자를 호출할 수 있다.")
public void reflection() throws Exception {
    Singleton1 singleton1 = Singleton1.INSTANCE;
    Singleton1 singleton1Reflection;

    Constructor<Singleton1> constructor = Singleton1.class.getDeclaredConstructor();
    constructor.setAccessible(true);
    singleton1Reflection = constructor.newInstance();

    Assertions.assertNotSame(singleton1, singleton1Reflection);
}
```
