### ISSUE TITLE
[아이템 5 - 질문] 한정적 와일드 카드 타입을 사용해 매개변수를 제한하는 것

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#30]
[질문]
29pg

한정적 와일드 카드 타입을 사용해 매개변수를 제한하여 팩터리에 활용한다고 하였는데, 한정적 와일드 카드 타입이 무엇인지 그리고 이게 어떻게 쓰여서 매개변수를 제한하여 팩터리에 활용되는지에 대한 예시

**Comment by cheewr85** [comment]
- 여기서 와일드 카드는 제네릭 코드에서 `?`로써 아직 알려지지 않은 타입을 말함

- 그래서 이 한정적 와일드 카드 타입을 통해서 팩터리의 타입 매개변수를 제한할 수 있음

- 이 방식을 사용해 클라이언트는 자신이 명시한 타입의 하위 타입이라면 무엇이든 생성할 수 있는 팩터리를 넘길 수 있음
```java
Mosaic create(Supplier<? extends Tile> tileFactory) { ... }
```

- 즉 말그대로 이를 통해서 타입을 제한을 했기 때문에 한정적 와일드 카드 타입을 사용해서 매개변수를 제한한다는 것임, 모든 타입이 자기 자신의 하위 타입이라고 볼 수 있음

------
### 참조
https://jaehun2841.github.io/2019/01/26/effective-java-item31/#%EC%84%9C%EB%A1%A0
https://hirlawldo.tistory.com/55

**Comment by riyenas0925** [comment]
### 한정적 와일드카드 (Bounded Wildcards)
#### Upper Bounded Wildcards (extends를 사용한 한정적 와일드카드)
타입의 제한을 풀어줄 때 사용합니다. 제네릭 타입들을 상위 제네릭 타입으로 묶어주는 방식
```java
public static void process(List<? extends Foo> list) { /* ... */ }
```
#### Lower Bounded Wildcards (super를 사용한 한정적 와일드 카드)
타입을 제한할 때 사용합니다. 유연성을 극대화하기 위해 지정된 타입의 상위 타입만 허용
```java
public static void addNumbers(List<? extends Integer> list) { /* ... */ }
```

### 참조
[[Java] 와일드 카드(Wildcards)](https://snoop-study.tistory.com/113)
