### ISSUE TITLE
[아이템 8-질문] 네이티브 피어란?

### ISSUE THREAD

**Issue by riyenas0925** [Study-Mornda/Effective-Java#35]
[질문]
43pg

네이티브 피어에 대한 예시를 통한 설명

**Comment by cheewr85** [comment]
- 네이티브 피어란 자바로 만든것이 아닌 C, C++ 같은 언어로 작성된 것을 의미함, 그래서 네이티브 메서드는 이런 언어로 작성한 메서드고 네이티브 피어는 이런 상황에서 자바 객체가 네이티브 메서드를 통해 기능수행을 위임한 상황을 말함

- 그래서 이 상황에서는 메모리 할당과 gc에서 처리를 하지 못함 네이티브 메서드로 위임이되서 자원의 반납 여부를 알 수 없기 때문임

- 그래서 예시라기보단 이 개념을 알면 될 것 같음, 그래서 이런 경우 finalizer나 cleaner를 통한 객체 소멸을 할 수 있다고 말하는 것임

------
### 참조
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=kbh3983&logNo=220908731253
https://stackoverflow.com/questions/48260485/what-is-a-native-peer
