### ISSUE TITLE
[아이템 7-질문] WeakHashMap을 사용해 캐시를 만드는 것

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#39]
[질문] 
38pg

엔트리가 살아있는 것, 여기서 엔트리가 무엇인지?
이렇게 엔트리가 살아 있는 캐시가 필요한 상황에서 WeakHashMap을 쓴다고 했는데 이 WeakHashMap은 무엇이고 어떻게 쓰이는 것인지?

**Comment by cheewr85** [comment]
- 여기서 엔트리가 살아있다고 나왔는데 캐시를 사용하면서 쓰이는 용어임

- 여기서 엔트리는 캐시에서 메모리 내 여러 주소값 목록이 적재된 곳임, 그래서 이렇게 캐시에서 엔트리가 살아있는 상황에서 WeakHashMap을 쓴다는 것

- WeakHashMap는 Map의 형태이므로 Key와 Value 한 쌍으로 이루어져 있어서 이 상황에서 쓴다는 것임, 여기서 WeakHashMap은 Key에 대한 참조가 더 이상 존재하지 않게 되면, Value를 가져올 수 있는 방법이 없다고 판단하여 Key-Value 쌍이 자동으로 삭제되는 Map임

- 그래서 책에서 외부에서 Key를 참조하는 동안만 엔트리가 살아있는 캐시가 필요한 상황에서 WeakHashMap을 쓰면 된다고 한 것, 캐시로 사용한 경우 자동으로 다 쓴 엔트리를 즉시 삭제하기 때문에

- 이를 사용하는 것은 Map을 쓰는 방식과 동일함

-------
### 참고
https://kimtaehyun98.tistory.com/48
https://yhmane.tistory.com/152
https://camel-context.tistory.com/42

**Comment by riyenas0925** [comment]
https://blog.riyenas.dev/70
