### ISSUE TITLE
[아이템 7-질문] 약한 참조

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#40]
[질문]
39pg

약한 참조를 어떻게 써서 콜백을 저장하는 것인지, 약한 참조에 대해서

**Comment by cheewr85** [comment]
- 약한 참조는 앞서 WeakHashMap에서 본 것 같은 경우를 볼 수 있음 즉, 자동으로 제거가 될 수 있는 상황을 의미함

- 여기서 콜백을 등록만 하고 명확히 해지하지 않으면 콜백이 쌓인다는데 이때 약한 참조를 쓴다는 것인데 앞서 말한 WeakHashMap을 쓸 수 있음

- 여기서 아예 콜백에서 WeakHashMap으로 설정을 해서 약한 참조를 걸어서 gc의 제거 대상으로 처리할 수 있게 할 수 있음

-----
### 참고
http://blog.breakingthat.com/2018/08/26/java-collection-map-weakhashmap/
https://javabom.tistory.com/14

**Comment by riyenas0925** [comment]
### 참고
https://lion-king.tistory.com/entry/Java-%EC%B0%B8%EC%A1%B0-%EC%9C%A0%ED%98%95-Strong-Reference-Soft-Reference-Weak-Reference-Phantom-References
