### ISSUE TITLE
[아이템 10-질문] AutoValue 프레임워크

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#47]
[질문]
65pg

equals 작성하고 테스트하는 일을 AutoValue 애너테이션이 처리해준다는데 이 애너테이션이 무엇이고 어떻게 테스트 해주는지

**Comment by cheewr85** [comment]
- 이 자동으로 처리해준다는 것이 우선 이 아이템에서는 주로 equals에 대해서 다루었지만 그처럼 직접 다 equals를 재정의해주고 이런 작업들을 반복적으로 하면 상당히 피로도가 높아지는 작업임

- 이를 AutoValue 어노테이션을 통해서 해결할 수 있음, 추상 클래스로 만들고 어노테이션을 붙이면 자동으로 해당 클래스 기준으로 equals라던지 번거로운 작업들이 알아서 해결이 됨

------
### 참고
[@AutoValue에 대하여](https://sdusb.blogspot.com/2017/04/android-antovalue.html?m=1)

**Comment by riyenas0925** [comment]
AutoValue, Lombok, Immutables와 같이 자바의 상용구 코드(getter, equals, toString ...)를 자동으로 생성해주는 라이브러리
