### ISSUE TITLE
[아이템 18-질문] 계측기능

### ISSUE THREAD

**Issue by cheewr85** [Study-Mornda/Effective-Java#68]
[질문]

119pg

계측할 수 있다고 하고 계측 기능이라고 하는데 정확히 자바에서의 계측 기능은 무엇을 의미하는 것인가

**Comment by cheewr85** [comment]
- 용어의 문제인 듯 싶음

- 계측이란 단어의 사전적 의미를 보면 단순히 양적으로 파악하는 측정을 넘어서 측정 결과를 따라 연산과 필요한 정보를 얻어 정보를 바탕으로 어떤 조치를 취하는 그런 의미라고 함

- 일단 대략적으로 이런 뜻임을 알고 다시 책의 내용을 보면 Set의 계측 기능을 활용한다고 하였는데 이는 어떠한 Set을 구현하더라도 단순히 상속받아서 하는 것이 아닌 컴포지션을 통해서 Set과 관련된 기능을 이용하고 Set이라는 컬렉션에 대해서 단순히 count를 세는것, 혹은 증가 제거 등 set의 기본적인 연산에 대한 기본적인 계측하는 역할을 쓸 수 있기 때문에 계측 기능을 쓰고 계측이라는 말을 하는 것임

**Comment by kimhanui** [comment]
여기서의 계측기능은 Item18의 예시로서 사용된 `Set을 확장해 추가된 원소의 수를 세는 기능`을 말하는 것 같습니다!
