### ISSUE TITLE
[아이템 7] 다 쓴 객체 참조를 해제하라 

### ISSUE THREAD

**Issue by kimhanui** [Study-Mornda/Effective-Java#7]
아이템 : 다 쓴 객체 참조를 해제하라

질문 

- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40

**Comment by riyenas0925** [comment]
답변
* String은 new가 아닌 리터럴 방식으로 생성될 경우 (String a = “abc”; 와 같이)  intern()에 의해 String pool을 JVM은 사용하므로 key가 null이 된다고 하도 WeakHashMap은 자동으로 삭제되지 않는다. 이는 Integer 와 같은 Class의 (-127 ~128) 값들도 마찬가지 이다.  JVM은 미리 불변 객체로 해당 값을 보관하고 있다.
